# Generated by Django 5.2.7 on 2025-10-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('tech_stack', models.TextField()),
            ],
        ),
    ]
